### ISSUE TITLE
Possible conflict with the latest versions of rack

### ISSUE THREAD

**Issue by fidalgo** [romanbsd/heroku-deflater#48]
As of rack 2.1.1 I always get this kind of error:

```
2020-01-27T17:55:25.393308+00:00 app[web.1]: I, [2020-01-27T17:55:25.393231 #3]  INFO -- : [64d627de-3d78-4643-9fe3-6a8f911cbc5a] Completed 302 Found in 43ms (ActiveRecord: 19.5ms | Allocations: 8776)
2020-01-27T17:55:25.394704+00:00 app[web.1]: 2020-01-27 17:55:25 +0000: Read error: #<NoMethodError: undefined method `each' for nil:NilClass>
2020-01-27T17:55:25.394707+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.1.1/lib/rack/deflater.rb:90:in `each'
2020-01-27T17:55:25.394708+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.1.1/lib/rack/body_proxy.rb:34:in `each'
2020-01-27T17:55:25.394709+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.1.1/lib/rack/body_proxy.rb:34:in `each'
2020-01-27T17:55:25.394711+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.1.1/lib/rack/body_proxy.rb:34:in `each'
2020-01-27T17:55:25.394712+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.1.1/lib/rack/body_proxy.rb:34:in `each'
2020-01-27T17:55:25.394713+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.1.1/lib/rack/body_proxy.rb:34:in `each'
2020-01-27T17:55:25.394715+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/server.rb:814:in `handle_request'
2020-01-27T17:55:25.394716+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/server.rb:472:in `process_client'
2020-01-27T17:55:25.394717+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/server.rb:328:in `block in run'
2020-01-27T17:55:25.394719+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```
I've also tried the https://github.com/rack/rack/commit/25c5820470e96f306404ecde901c57cff9d42305 version of rack and it gives me the same error.

Removing `heroku-deflater` from the Gemfile makes the error go away.

**Comment by andrewmcodes** [comment]
@fidalgo do you get the same issue with 2.2.2?

**Comment by fidalgo** [comment]
@andrewmcodes Haven't tried yet, but I guess I will not be using this gem anymore.
